name: flutter_twitter_login_example
description: Demonstrates how to use the flutter_twitter_login plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 #https://pub.dev/packages/cupertino_icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_twitter_login:
    path: ../

flutter:
  uses-material-design: true
